import math
print (40*'=')
print ('MENGHITUNG PANJANG KAPAL'.center(40))
print (40*'=')
h = float(input('Masukkan tinggi menara\n(dalam meter)'.ljust(30)+': '.rjust(19)))
a = float(input('Masukkan sudut pengamat\nterhadap buritan kapal'.ljust(30)+': '.rjust(11)))
b = float(input('Masukkan sudut pengamat\nterhadap haluan kapal'.ljust(30)+': '.rjust(11)))
ang_a = math.radians(a)
ang_b = math.radians(b)
tan_a = math.tan(ang_a)
tan_b = math.tan(ang_b)
long = round(h*(tan_a-tan_b),1)
print (40*'=')
print (f'{"Panjang kapal":<30}: {long}m')
print (40*'=')
print ('TERIMA KASIH'.center(40))
print (40*'=')