print (40*'=')
print ("KONVERSI DETIK KE FORMAT JAM:MENIT:DETIK".ljust(40))
print (40*"=")
x = int(input('Masukkan waktu dalam detik'.ljust(30)+':'))
print (' ')
jam = "{:02d}".format(x//3600)
mnt = "{:02d}".format((x%3600)//60)
dtk = "{:02d}".format(((x%3600)%60))
print (f'{jam} jam {mnt} menit {dtk} detik'.center(40))
print (' ')
print (40*'=')
print ('TERIMA KASIH'.center(40))
print (40*'=')